spring:
  profiles:
    active: dev
  application:
    name: search-provider
mybatis:
  mapper-locations: classpath*:com/gpmall/pay/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.pay.dal.entitys
server:
  port: 8200


