spring:
  application:
    name: gpmall-sso

dubbo:
  application:
    name: gpmall-sso
    owner: Mic
  registry:
    address: zookeeper://192.168.1.105:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.1.105:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.gpmall.sso

