dubbo:
  application:
    name: gpmall-user
    owner: Mic
  registry:
    address: zookeeper://192.168.13.106:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.13.106:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.gpmall.user

swagger :
  name : test
  title: titles

captchaFlag : false